# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 964e1b7a7933a485885ee9c3412977da5a01a89d224a709fc939fe8131859c7bde0f92237a5c38c6898b434bc0c684b4349c1782a86477ba38e40cfec3b6ffa9

test:
  secret_key_base: a44c73f1cb52f12cd3712633aef3edc05b259cbcf5e5c84642b608b088c9cb9246e7bb5f7dd66e9440a78029b5f62d2037548bca6cf1c44a0f82bc78a0ce7f0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
